volumes:
  db_data:
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: silent-pay-indexer
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
