services:
  bitcoin:
    image: btcpayserver/bitcoin:24.0.1-1
    environment:
      BITCOIN_NETWORK: regtest
      BITCOIN_EXTRA_ARGS: |
        server=1
        rest=1
        rpcbind=0.0.0.0:18443
        rpcallowip=0.0.0.0/0
        rpcuser=polaruser
        rpcpassword=password
        debug=1
        logips=1
        logtimemicros=1
        blockmintxfee=0
        deprecatedrpc=signrawtransaction
        listenonion=0
        fallbackfee=0.00001
        txindex=1
    ports:
      - '18443:18443'