services:
  bitcoin:
    image: btcpayserver/bitcoin:24.0.1-1
    environment:
      BITCOIN_NETWORK: regtest
      BITCOIN_EXTRA_ARGS: |
        server=1
        rest=1
        rpcbind=0.0.0.0:18443
        rpcallowip=0.0.0.0/0
        rpcauth=polaruser:29fc7c114646a46c59c029eb076a0967$a985383e5b88d84acf241765c558c408b3fed0ab887575568b4e7fb8e77af6e4
        debug=1
        logips=1
        logtimemicros=1
        blockmintxfee=0
        deprecatedrpc=signrawtransaction
        listenonion=0
        fallbackfee=0.00001
        txindex=1
    ports:
      - '18443:18443'