db:
  path: ~/.silent-pay-indexer/db/database.sqlite
  synchronize: false
app:
  port: <port>
  verbose: <boolean>
  debug: <boolean>
  network: <network>
  requestRetry:
    delay: <number> # delay in Milliseconds
    count: <number> 
providerType: <providerType>
esplora:
  url: <host>
  batchSize: <batchSize>
bitcoinCore:
  protocol: <http | https>
  rpcHost: <host>
  rpcPass: <password>
  rpcUser: <username>
  rpcPort: <port>
    
