db:
  path: ~/.silent-pay-indexer/db/database.sqlite
  synchronize: false
app:
  port: <port>
  network: <network>
providerType: <providerType>
esplora:
  url: <host>
  batchSize: <batchSize>
bitcoinCore:
  protocol: <http | https>
  rpcHost: <host>
  rpcPass: <password>
  rpcUser: <username>
  rpcPort: <port>
