db:
  host: <host>
  port: <port>
  username: <username>
  password: <password>
  databaseName: silent-pay-indexer
  synchronize: false
app:
  port: <port>
  network: <network>
providerType: <providerType>
esplora:
  url: <host>
  batchSize: <batchSize>
bitcoinCore:
  protocol: <http | https>
  rpcHost: <host>
  rpcPass: <password>
  rpcUser: <username>
  rpcPort: <port>
