db:
  host: localhost
  port: 5432
  username: root
  password: password
  databaseName: silent-pay-indexer
  synchronize: true
app:
  port: 3000
  network: regtest
providerType: ESPLORA
esplora:
  url: <url>
