db:
  host: localhost
  port: 5432
  username: root
  password: password
  databaseName: silent-pay-indexer
  synchronize: true
app:
  port: 3000
  network: regtest
providerType: ESPLORA
esplora:
  url: https://blockstream.info
  batchSize: 5
bitcoinCore:
  rpcHost: 127.0.0.1
  rpcPass: polarpass
  rpcUser: polaruser
  rpcPort: 18445
