db:
  path: ./.silent-pay-indexer/db/database.sqlite
  synchronize: true
app:
  port: 3000
  network: regtest
  requestRetry:
    delay: 3000
    count: 3
providerType: ESPLORA
esplora:
  url: https://blockstream.info
  batchSize: 5
bitcoinCore:
  protocol: http
  rpcHost: 127.0.0.1
  rpcPass: polarpass
  rpcUser: polaruser
  rpcPort: 18445
    
