db:
  path: ':memory:'
  synchronize: true
app:
  port: 3000
  schedulerInterval: 10
  network: regtest
  requestRetry:
    delay: 500
    count: 1
providerType: BITCOIN_CORE_RPC
bitcoinCore:
  protocol: http
  rpcHost: localhost
  rpcPass: password
  rpcUser: polaruser
  rpcPort: 18443
