db:
  path: ':memory:'
  synchronize: true
app:
  port: 3000
  verbose: false
  debug: true
  network: regtest
  requestRetry:
    delay: 500
    count: 1
providerType: BITCOIN_CORE_RPC
bitcoinCore:
  protocol: http
  rpcHost: localhost
  rpcPass: password
  rpcUser: polaruser
  rpcPort: 18443
throttler:
  ttl: 1000
  limit: 5
cache:
  ttl: 5000 # 5 sec
