db:
  path: '~/.silent-pay-indexer/db/database.sqlite'
  synchronize: false
app:
  port: 80
  verbose: false
  debug: true
  network: regtest
  requestRetry:
    delay: 500 # delay in Milliseconds
    count: 3
providerType: BITCOIN_CORE_RPC
bitcoinCore:
  protocol: http # http | https
  rpcHost: localhost
  rpcPass: password
  rpcUser: polaruser
  rpcPort: 18443
throttler:
  ttl: 1000 # 1 sec
  limit: 5 # 5 requests
cache:
  ttl: 5000 # 5 sec
