name: 'Lint'
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
jobs:
  check-formatting-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.x
          cache: npm
      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
      - name: Install Dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm install
      - name: Run prettier
        run: npm run format:check
      - name: Run eslint
        if: success() || failure()
        run: npm run lint:check
      - name: Run Typescript Compilation Check
        run: npm run types:check